# Generated by Django 3.1.7 on 2021-03-02 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_set_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profiles', serialize=False, to='main.user')),
                ('phone', models.CharField(max_length=15, null=True)),
                ('mobile', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=200)),
                ('avatar', models.ImageField(max_length=255, null=True, upload_to='')),
            ],
        ),
    ]
