# Generated by Django 3.1.7 on 2021-04-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210327_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='headshot',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='users/'),
        ),
    ]
