# Generated by Django 3.1.7 on 2021-04-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='no_image.jpeg', null=True, upload_to='articles/'),
        ),
    ]
